[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
FourVectors = "b122eb78-8380-428a-b8c8-584a022ae8b6"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LazyDecayAngles = "1d606af4-d0f8-4ff7-bc8d-eb3f657b7647"
